spring:
  datasource:
    url: jdbc:mysql://${mysql.host}/vacinas?createDatabaseIfNotExist=true&useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${mysql.username}
    password: ${mysql.password}
  liquibase:
    change-log: liquibase/master.yaml
  profiles:
    active: dev

  jpa:
    show-sql: ${show-sql:false}

server:
  port: 8081